GET http://localhost:5085/games

###
GET http://localhost:5085/games/4
###
POST http://localhost:5085/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genre": "Survival",
  "price": 10.0,
  "releaseDate": "2020-01-01"
}

###
PUT http://localhost:5085/games/1
Content-Type: application/json

{
  "name": "Minecraft",
  "genre": "Survival",
  "price": 10.0,
  "releaseDate": "2020-01-01"
}

###
DELETE http://localhost:5085/games/1
